language: crystal
before_install:
  - wget -O - http://debian.neo4j.org/neotechnology.gpg.key | apt-key add -
  - echo 'deb http://debian.neo4j.org/repo stable/' > /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update
  - sudo apt-get install neo4j
  - sudo service neo4j start
  - while [ $? -ne 0 ]; do; curl -I http://localhost:7474 |head -1 | grep 200; done
